/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange Telegram Mini App init data for a session
         * @description Validates the raw query string according to Telegram's Mini App algorithm,
         *     rejects `auth_date` older than five minutes, upserts the Telegram identity,
         *     and sets a seven-day Secure, HttpOnly, SameSite session cookie. Data from
         *     `initDataUnsafe` is never accepted.
         */
        post: operations["authenticateTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current identity and onboarding state */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create identity-bound group and channel join-request links
         * @description Creates or replaces 30-minute join-request links for the authenticated
         *     Telegram identity. Only that identity may be approved. Links are revoked
         *     after approval or replacement.
         */
        post: operations["createOnboardingInvites"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/membership/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recheck canonical group and channel membership
         * @description Calls Telegram `getChatMember` for both configured chats and advances onboarding only when both memberships are valid.
         */
        post: operations["checkOnboardingMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/username": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reserve the immutable service username
         * @description Accepts only `^[a-z]{3,9}$`. The service checks local uniqueness, performs
         *     a Remnawave preflight, and also treats Remnawave `A019` as a duplicate if
         *     the upstream race is lost.
         */
        put: operations["reserveUsername"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/agreement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept the no-sharing agreement and provision Remnawave
         * @description Records acceptance and ensures an ACTIVE Remnawave user with a 2099
         *     upstream expiry, zero traffic, NO_RESET, and no squads. Recoverable partial
         *     failures remain resumable and are reconciled by username and Telegram ID.
         */
        post: operations["acceptSharingAgreement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current home-page projection
         * @description Returns balance, active and queued purchases, subscription data, and cached Remnawave statistics. `statisticsStale` is true when cached statistics were used after an upstream failure.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List purchasable combos and add-on squads */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's purchase history */
        get: operations["listPurchases"];
        put?: never;
        /**
         * Purchase or renew a combo with optional squads
         * @description Prices are loaded from the current catalog and debited atomically from the
         *     TXB ledger. First purchases activate immediately, same-plan renewals extend
         *     from the later of now or current expiry, and plan/add-on changes queue for
         *     the current term boundary. No proration is performed.
         */
        post: operations["createPurchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscription/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the current Remnawave subscription URL
         * @description Calls Remnawave revoke with `revokeOnlyPasswords:false`. The old URL must be treated as invalid after success.
         */
        post: operations["revokeSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current TXB balance */
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's immutable TXB ledger */
        get: operations["listLedgerEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a balance top-up order
         * @description The requested TXB minor units are converted using the current fixed-decimal
         *     dashboard rate. Provider payable amounts are rounded upward to provider
         *     precision. A successful authoritative callback credits exactly `txbMinor`.
         */
        post: operations["createPaymentOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll durable payment state */
        get: operations["getPaymentOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List dashboard configuration
         * @description Sensitive values return an empty `value` plus `encrypted` and `configured`; plaintext and ciphertext are never returned.
         */
        get: operations["listAdminSettings"];
        put?: never;
        /** Validate and write a known dashboard setting */
        post: operations["createAdminSetting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Validate and replace one dashboard setting
         * @description The setting registry decides whether a value is encrypted with AES-256-GCM. Clients cannot downgrade secret storage to plaintext.
         */
        put: operations["updateAdminSetting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/combos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all combos, including inactive records */
        get: operations["listAdminCombos"];
        put?: never;
        /** Create a validated combo */
        post: operations["createAdminCombo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/combos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a combo's future-sale definition
         * @description Existing purchases retain their stored catalog snapshot.
         */
        put: operations["updateAdminCombo"];
        post?: never;
        /**
         * Archive a combo from future sales
         * @description This is a soft archive. Historical purchases and audit records remain intact.
         */
        delete: operations["archiveAdminCombo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/squad-products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List imported Remnawave squad products */
        get: operations["listAdminSquadProducts"];
        put?: never;
        /** Create a local product for an existing Remnawave squad */
        post: operations["createAdminSquadProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/squad-products/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconcile local squad products from Remnawave
         * @description Imports upstream squads and marks missing upstream records unavailable without deleting purchase history.
         */
        post: operations["importAdminSquadProducts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/squad-products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set a squad product's local merchandising fields */
        put: operations["updateAdminSquadProduct"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users through safe projections */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one safe user identity projection */
        get: operations["getAdminUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/balance-adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append an audited manual TXB adjustment
         * @description Never edits or deletes an existing ledger row. A non-empty reason is required.
         */
        post: operations["adjustAdminUserBalance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active, queued, and historical entitlements */
        get: operations["listAdminEntitlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/entitlements/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel queued or active access with an audit reason */
        post: operations["cancelAdminEntitlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payment orders and authoritative states */
        get: operations["listAdminPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/payments/{id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append an immutable payment reversal
         * @description Reverses the credited TXB exactly once. If the balance becomes negative,
         *     queued purchases are cancelled first, then active purchases newest-first,
         *     and Remnawave revocations are queued. Remaining debt blocks purchases.
         */
        post: operations["refundAdminPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable refund records */
        get: operations["listAdminRefunds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List verified online database backups */
        get: operations["listAdminBackups"];
        put?: never;
        /** Run and verify an online SQLite backup now */
        post: operations["createAdminBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persistent outbox and scheduler jobs */
        get: operations["listAdminJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make a failed retryable job available now */
        post: operations["retryAdminJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable administrative audit events */
        get: operations["listAdminAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive Telegram bot updates
         * @description Validates the configured Telegram webhook secret header. Relevant join requests, chat-member updates, pre-checkout queries, and successful payments are processed idempotently.
         */
        post: operations["receiveTelegramWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/ezpay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Receive the signed EZPay asynchronous notification
         * @description Only a valid signature, `TRADE_SUCCESS`, known order/provider trade, and exact payable amount can credit TXB. Replayed notifications are acknowledged without a second credit.
         */
        get: operations["receiveEZPayWebhook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/bepusdt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a signed BEPusdt transaction notification
         * @description Status `2` is the only crediting state. Signature, local order, provider trade ID,
         *     requested USD amount, and actual crypto amount are checked before the idempotent
         *     ledger transaction. When the callback's overloaded `token` field carries a receiving
         *     address, it must exactly match the checkout address; the reference-compatible literal
         *     `USDT` token is treated as a currency marker. Status `3` is validated against the same
         *     durable order snapshot before the order is marked expired.
         */
        post: operations["receiveBEPusdtWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/return/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Navigate back to the Mini App after provider checkout
         * @description This route never credits balance. It redirects to the client order screen, which polls durable webhook-confirmed state.
         */
        get: operations["returnFromPaymentProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/return/{provider}/{orderID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Navigate back to a specific Mini App payment order
         * @description Compatibility return route for providers that preserve path parameters more reliably than query parameters. It never credits balance.
         */
        get: operations["returnFromPaymentProviderWithOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** HTTP and local database liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database and setup readiness
         * @description Returns 503 until the database is usable and required chat, Remnawave, exchange-rate, and catalog configuration is complete.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 01JZX6BKW16M0CNQ5Q74K8DN7J */
        ID: string;
        /**
         * Format: date-time
         * @example 2026-08-07T10:00:00Z
         */
        Timestamp: string;
        /** @example 1250 */
        DecimalInteger: string;
        ApiError: {
            /** @example INSUFFICIENT_BALANCE */
            code: string;
            message: string;
            details?: {
                [key: string]: string;
            };
            requestId?: string;
        };
        TelegramAuthRequest: {
            /** @description Raw `Telegram.WebApp.initData` query string. */
            initData: string;
        };
        /** @enum {string} */
        OnboardingStep: "intro" | "membership" | "username" | "agreement" | "complete";
        User: {
            id: components["schemas"]["ID"];
            telegramId: string;
            firstName: string;
            lastName: string;
            telegramUsername: string;
            username: string | null;
            /** @enum {string} */
            role: "user" | "admin";
            onboardingState: components["schemas"]["OnboardingStep"];
            groupJoined: boolean;
            channelJoined: boolean;
            /** Format: date-time */
            policyAcceptedAt: string | null;
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        AuthState: {
            /** @constant */
            authenticated: true;
            user: components["schemas"]["User"];
        };
        JoinInvite: {
            /** Format: uri */
            url: string;
            expiresAt: components["schemas"]["Timestamp"];
        };
        OnboardingInvites: {
            group: components["schemas"]["JoinInvite"];
            channel: components["schemas"]["JoinInvite"];
        };
        MembershipState: {
            groupJoined: boolean;
            channelJoined: boolean;
            complete: boolean;
            user: components["schemas"]["User"];
        };
        UsernameRequest: {
            username: string;
        };
        AgreementRequest: {
            /** @constant */
            accepted: true;
        };
        /** @description Integer minor units. TXB, CNY, and USD use scale 2; XTR uses scale 0. */
        Money: {
            /** @enum {string} */
            currency: "TXB" | "CNY" | "USD" | "XTR";
            minor: components["schemas"]["DecimalInteger"];
            /** @description Server-formatted display value; never parse this for calculations. */
            display: string;
        };
        PaymentMethod: {
            provider: components["schemas"]["PaymentProvider"];
            name: string;
            /** @enum {string} */
            currency: "CNY" | "USD" | "USDT" | "XTR";
            available: boolean;
            note: string;
        };
        BalanceResponse: {
            balance: components["schemas"]["Money"];
            paymentMethods: components["schemas"]["PaymentMethod"][];
        };
        /** @enum {string} */
        ResetStrategy: "DAY" | "WEEK" | "MONTH";
        SquadProduct: {
            id: components["schemas"]["ID"];
            /** Format: uuid */
            remnaSquadUuid: string;
            name: string;
            description: string;
            price: components["schemas"]["Money"];
            visible: boolean;
            upstreamPresent: boolean;
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        Combo: {
            id: components["schemas"]["ID"];
            name: string;
            description: string;
            price: components["schemas"]["Money"];
            validityDays: number;
            trafficLimitBytes: string;
            resetStrategy: components["schemas"]["ResetStrategy"];
            includedSquads: components["schemas"]["SquadProduct"][];
            active: boolean;
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        Catalog: {
            combos: components["schemas"]["Combo"][];
            addons: components["schemas"]["SquadProduct"][];
        };
        ComboWrite: {
            name: string;
            description: string;
            priceTxbMinor: string;
            validityDays: number;
            trafficLimitBytes: string;
            resetStrategy: components["schemas"]["ResetStrategy"];
            squadProductIds: components["schemas"]["ID"][];
            active: boolean;
        };
        SquadProductWrite: {
            /** Format: uuid */
            remnaSquadUuid: string;
            name: string;
            description: string;
            priceTxbMinor: string;
            visible: boolean;
        };
        PurchaseRequest: {
            comboId: components["schemas"]["ID"];
            addonSquadProductIds: components["schemas"]["ID"][];
        };
        /** @enum {string} */
        EntitlementStatus: "activating" | "active" | "queued" | "expired" | "cancelled" | "failed";
        Entitlement: {
            id: components["schemas"]["ID"];
            comboId: components["schemas"]["ID"];
            comboName: string;
            squadIds: string[];
            status: components["schemas"]["EntitlementStatus"];
            startsAt: components["schemas"]["Timestamp"];
            endsAt: components["schemas"]["Timestamp"];
            trafficLimitBytes: string;
            resetStrategy: components["schemas"]["ResetStrategy"];
        };
        Purchase: {
            id: components["schemas"]["ID"];
            comboId: components["schemas"]["ID"];
            comboName: string;
            price: components["schemas"]["Money"];
            validFrom: components["schemas"]["Timestamp"];
            validUntil: components["schemas"]["Timestamp"];
            status: components["schemas"]["EntitlementStatus"];
            trafficLimitBytes: string;
            resetStrategy: components["schemas"]["ResetStrategy"];
            squadUuids: string[];
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        /** @description The URL is a bearer credential and must not be logged, cached outside the authenticated UI, or exposed through admin list endpoints. */
        SubscriptionRotation: {
            /** Format: uri */
            subscriptionUrl: string;
        };
        TopNode: {
            uuid: string;
            name: string;
            countryCode: string;
            totalBytes: string;
        };
        Statistics: {
            usedTrafficBytes: string;
            lifetimeTrafficBytes: string;
            trafficLimitBytes: string;
            /** Format: date-time */
            onlineAt: string | null;
            categories: string[];
            sparklineData: string[];
            topNodes: components["schemas"]["TopNode"][];
        };
        Dashboard: {
            user: components["schemas"]["User"];
            balance: components["schemas"]["Money"];
            activePurchase: components["schemas"]["Purchase"] | null;
            queuedPurchase: components["schemas"]["Purchase"] | null;
            statistics: components["schemas"]["Statistics"] | null;
            /** Format: uri */
            subscriptionUrl: string | null;
            statisticsStale: boolean;
            statisticsWarning: string;
            fetchedAt: components["schemas"]["Timestamp"];
        };
        /** @enum {string} */
        LedgerKind: "payment_credit" | "payment_reversal" | "purchase_debit" | "purchase_cancellation" | "admin_adjustment" | "admin_entitlement_cancellation";
        LedgerEntry: {
            id: components["schemas"]["ID"];
            delta: components["schemas"]["Money"];
            balanceAfter: components["schemas"]["Money"];
            kind: components["schemas"]["LedgerKind"];
            referenceId: string;
            note: string;
            createdAt: components["schemas"]["Timestamp"];
        };
        PageInfo: {
            nextCursor: string | null;
        };
        LedgerPage: {
            items: components["schemas"]["LedgerEntry"][];
            page?: components["schemas"]["PageInfo"];
        };
        /** @enum {string} */
        PaymentProvider: "ezpay" | "bepusdt" | "stars";
        /** @enum {string} */
        PaymentStatus: "creating" | "pending" | "paid" | "expired" | "failed" | "refunded";
        PaymentOrderRequest: {
            provider: components["schemas"]["PaymentProvider"];
            txbMinor: string;
        };
        PaymentOrder: {
            id: components["schemas"]["ID"];
            provider: components["schemas"]["PaymentProvider"];
            status: components["schemas"]["PaymentStatus"];
            txb: components["schemas"]["Money"];
            payableAmount: string;
            /** @enum {string} */
            payableCurrency: "CNY" | "USD" | "XTR" | "USDT";
            /** @description Fixed-decimal rate used when the order was created. */
            rateSnapshot: string;
            /** Format: uri */
            paymentUrl: string | null;
            qrPayload: string | null;
            expiresAt: components["schemas"]["Timestamp"];
            /** Format: date-time */
            paidAt: string | null;
            /** Format: date-time */
            refundedAt: string | null;
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        AdminSetting: {
            key: string;
            /** @description Empty for encrypted settings; plaintext and ciphertext are never returned. */
            value: string;
            encrypted: boolean;
            configured: boolean;
            /** @enum {string} */
            category: "telegram" | "remnawave" | "rates" | "payments" | "application";
            updatedAt: components["schemas"]["Timestamp"];
        };
        AdminSettingCreate: {
            key: string;
            value: string;
        };
        AdminSettingUpdate: {
            value: string;
        };
        AdminUserSummary: {
            user: components["schemas"]["User"];
            balance: components["schemas"]["Money"];
            createdAt: components["schemas"]["Timestamp"];
            synchronization: {
                /** @enum {string} */
                status: "synchronized" | "not_provisioned";
            };
        };
        AdminUserPage: {
            items: components["schemas"]["AdminUserSummary"][];
            page?: components["schemas"]["PageInfo"];
        };
        BalanceAdjustmentRequest: {
            deltaTxbMinor: string;
            reason: string;
        };
        ReasonRequest: {
            reason: string;
        };
        EntitlementPage: {
            items: components["schemas"]["AdminEntitlement"][];
            page?: components["schemas"]["PageInfo"];
        };
        AdminEntitlement: {
            id: components["schemas"]["ID"];
            userId: components["schemas"]["ID"];
            comboId: components["schemas"]["ID"];
            comboName: string;
            price: components["schemas"]["Money"];
            validFrom: components["schemas"]["Timestamp"];
            validUntil: components["schemas"]["Timestamp"];
            status: components["schemas"]["EntitlementStatus"];
            trafficLimitBytes: string;
            resetStrategy: components["schemas"]["ResetStrategy"];
            squadUuids: string[];
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        PaymentPage: {
            items: components["schemas"]["AdminPaymentOrder"][];
            page?: components["schemas"]["PageInfo"];
        };
        AdminPaymentOrder: {
            id: components["schemas"]["ID"];
            userId: components["schemas"]["ID"];
            provider: components["schemas"]["PaymentProvider"];
            status: components["schemas"]["PaymentStatus"];
            txb: components["schemas"]["Money"];
            payableAmount: string;
            /** @enum {string} */
            payableCurrency: "CNY" | "USD" | "XTR" | "USDT";
            rateSnapshot: string;
            /** Format: uri */
            paymentUrl: string | null;
            qrPayload: string | null;
            expiresAt: components["schemas"]["Timestamp"];
            /** Format: date-time */
            paidAt: string | null;
            /** Format: date-time */
            refundedAt: string | null;
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        RefundRequest: {
            reason: string;
        };
        Refund: {
            id: components["schemas"]["ID"];
            paymentOrderId: components["schemas"]["ID"];
            actorUserId: string | null;
            txb: components["schemas"]["Money"];
            reason: string;
            /** @enum {string} */
            status: "completed";
            createdAt: components["schemas"]["Timestamp"];
        };
        RefundPage: {
            items: components["schemas"]["Refund"][];
            page?: components["schemas"]["PageInfo"];
        };
        BackupRun: {
            id: components["schemas"]["ID"];
            path: string;
            /** Format: int64 */
            sizeBytes: number;
            /** @enum {string} */
            status: "running" | "complete" | "failed";
            error: string;
            createdAt: components["schemas"]["Timestamp"];
            /** Format: date-time */
            completedAt: string | null;
        };
        /** @enum {string} */
        JobStatus: "pending" | "processing" | "done" | "failed";
        Job: {
            id: components["schemas"]["ID"];
            kind: string;
            aggregateId: string;
            /** @description JSON command payload; provider credentials and bearer URLs are never included. */
            payload: string;
            status: components["schemas"]["JobStatus"];
            attempts: number;
            availableAt: components["schemas"]["Timestamp"];
            /** @description Redacted operator-safe error summary. */
            lastError: string;
            createdAt: components["schemas"]["Timestamp"];
            updatedAt: components["schemas"]["Timestamp"];
        };
        JobPage: {
            items: components["schemas"]["Job"][];
            page?: components["schemas"]["PageInfo"];
        };
        AuditEvent: {
            id: components["schemas"]["ID"];
            actorUserId: string | null;
            action: string;
            targetType: string;
            targetId: string;
            /** @description Redacted JSON object encoded as a string. */
            detail: string;
            createdAt: components["schemas"]["Timestamp"];
        };
        AuditPage: {
            items: components["schemas"]["AuditEvent"][];
            page?: components["schemas"]["PageInfo"];
        };
        TelegramUpdate: {
            /** Format: int64 */
            update_id: number;
            chat_join_request?: {
                [key: string]: unknown;
            };
            chat_member?: {
                [key: string]: unknown;
            };
            pre_checkout_query?: {
                [key: string]: unknown;
            };
            message?: {
                successful_payment?: {
                    /** @constant */
                    currency?: "XTR";
                    total_amount?: number;
                    invoice_payload?: string;
                    telegram_payment_charge_id?: string;
                    provider_payment_charge_id?: string;
                } & {
                    [key: string]: unknown;
                };
                refunded_payment?: {
                    /** @constant */
                    currency?: "XTR";
                    total_amount?: number;
                    invoice_payload?: string;
                    telegram_payment_charge_id?: string;
                    provider_payment_charge_id?: string;
                } & {
                    [key: string]: unknown;
                };
            } & {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        FlexibleDecimal: string | number;
        BEPusdtNotification: {
            trade_id: string;
            order_id: string;
            amount: components["schemas"]["FlexibleDecimal"];
            actual_amount: components["schemas"]["FlexibleDecimal"];
            token: string;
            block_transaction_id?: string;
            /** @enum {integer} */
            status: 1 | 2 | 3;
            signature: string;
            created_at?: string;
            expired_at?: string;
        } & {
            [key: string]: unknown;
        };
        HealthStatus: {
            /** @constant */
            status: "ok";
        };
        RuntimeReadiness: {
            /** @enum {string} */
            status: "ok" | "setup_required" | "degraded";
            missing?: string[];
        };
    };
    responses: {
        /** @description Request validation failed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Missing, invalid, or expired authentication or provider signature. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description The authenticated identity cannot perform this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found or not visible to the caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Request conflicts with current persisted state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description The JSON shape was valid, but one or more domain values failed validation. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description A required local operation failed unexpectedly. */
        InternalFailure: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description A required provider could not complete the synchronous portion of the request. */
        UpstreamFailure: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description A required service or deployment setting is temporarily unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        ResourceID: string;
        SettingKey: string;
        /** @description Opaque cursor returned by the preceding page. */
        Cursor: string;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authenticateTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramAuthRequest"];
            };
        };
        responses: {
            /** @description Authenticated; the session cookie is set. */
            200: {
                headers: {
                    /** @description Opaque session cookie. Its value is never exposed to JavaScript. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOnboardingInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active one-time join-request links. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingInvites"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    checkOnboardingMembership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed canonical membership and user state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["UpstreamFailure"];
        };
    };
    reserveUsername: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsernameRequest"];
            };
        };
        responses: {
            /** @description Username reserved and onboarding advanced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    acceptSharingAgreement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgreementRequest"];
            };
        };
        responses: {
            /** @description Agreement accepted and onboarding complete. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthState"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["UpstreamFailure"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard projection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["UpstreamFailure"];
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current visible catalog. The server will recalculate all prices at purchase time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalFailure"];
        };
    };
    listPurchases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purchases newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Purchase"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalFailure"];
        };
    };
    createPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseRequest"];
            };
        };
        responses: {
            /** @description Purchase was created and its Remnawave operation was queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Purchase"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Insufficient balance, outstanding debt, stale catalog choice, or incompatible queued change. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    revokeSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated subscription reference. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionRotation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["UpstreamFailure"];
        };
    };
    getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current ledger-derived balance and enabled-provider availability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalFailure"];
        };
    };
    listLedgerEntries: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned by the preceding page. */
                cursor?: components["parameters"]["Cursor"];
                size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ledger entries newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalFailure"];
        };
    };
    createPaymentOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentOrderRequest"];
            };
        };
        responses: {
            /** @description Durable payment order, QR payload, and provider navigation target. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOrder"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            502: components["responses"]["UpstreamFailure"];
        };
    };
    getPaymentOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authoritative order state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOrder"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setting definitions and safe display values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminSetting"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminSetting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSettingCreate"];
            };
        };
        responses: {
            /** @description Setting stored; secret values remain write-only. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Unprocessable"];
        };
    };
    updateAdminSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["SettingKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSettingUpdate"];
            };
        };
        responses: {
            /** @description Setting replaced; secret values remain write-only. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listAdminCombos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrative combo list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Combo"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminCombo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComboWrite"];
            };
        };
        responses: {
            /** @description Created combo. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Combo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    updateAdminCombo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComboWrite"];
            };
        };
        responses: {
            /** @description Updated combo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Combo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    archiveAdminCombo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Combo archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminSquadProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Squad products, including hidden or unavailable records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SquadProduct"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminSquadProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SquadProductWrite"];
            };
        };
        responses: {
            /** @description Created squad product. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadProduct"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    importAdminSquadProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete reconciled squad-product list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SquadProduct"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["UpstreamFailure"];
        };
    };
    updateAdminSquadProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SquadProductWrite"];
            };
        };
        responses: {
            /** @description Updated squad product. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadProduct"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User page. Subscription bearer URLs are omitted from list results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domain-safe user identity without subscription bearer data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adjustAdminUserBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BalanceAdjustmentRequest"];
            };
        };
        responses: {
            /** @description Appended ledger entry. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listAdminEntitlements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entitlement page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    cancelAdminEntitlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description Cancellation recorded and Remnawave revocation queued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Purchase"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listAdminPayments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    refundAdminPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundRequest"];
            };
        };
        responses: {
            /** @description Refunded payment order after the immutable reversal and compensating work were recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentOrder"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            502: components["responses"]["UpstreamFailure"];
        };
    };
    listAdminRefunds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refund page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminBackups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup runs newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["BackupRun"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAdminBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup completed and verified. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listAdminJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job page. Secret payload fields are redacted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    retryAdminJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job scheduled for retry. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listAdminAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit page. Events cannot be updated or deleted through the API. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    receiveTelegramWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-Telegram-Bot-Api-Secret-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramUpdate"];
            };
        };
        responses: {
            /** @description Update accepted or already processed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalFailure"];
            502: components["responses"]["UpstreamFailure"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    receiveEZPayWebhook: {
        parameters: {
            query: {
                pid: string;
                trade_no: string;
                out_trade_no: string;
                type: string;
                name?: string;
                money: string;
                trade_status: "TRADE_SUCCESS";
                sign: string;
                sign_type: "MD5";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plain-text `success` for a valid notification, including an idempotent replay. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": "success";
                };
            };
            /** @description Signature or notification validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": "fail";
                };
            };
            /** @description The signed payment did not match durable order state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": "fail";
                };
            };
        };
    };
    receiveBEPusdtWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BEPusdtNotification"];
            };
        };
        responses: {
            /** @description Configured plain-text acknowledgement; defaults to `ok`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    returnFromPaymentProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "ezpay" | "bepusdt";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the same-origin payment result route. */
            303: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    returnFromPaymentProviderWithOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "ezpay" | "bepusdt";
                orderID: components["schemas"]["ID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the same-origin payment result route. */
            303: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process can serve HTTP and SQLite responds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description The process is serving HTTP but SQLite is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve the complete product. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeReadiness"];
                };
            };
            /** @description Alive but not fully configured or a required local dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeReadiness"];
                };
            };
        };
    };
}
