package httpapi

import (
	"github.com/go-chi/chi/v5"
)

func (s *Server) mountAdmin(router chi.Router) {
	s.mountCommunityAdmin(router)
	router.Get("/emby-accounts", s.adminEmbyAccounts)
	router.Post("/emby-accounts/{id}/retry", s.retryAdminEmbyAccount)
	router.Get("/settings", s.adminSettings)
	router.Post("/settings", s.adminCreateSetting)
	router.Put("/settings/{key}", s.adminUpdateSetting)
	router.Get("/payment-profiles", s.adminPaymentProfiles)
	router.Put("/payment-profiles/{provider}", s.adminSavePaymentProfile)
	router.Get("/combos", s.adminCombos)
	router.Post("/combos", s.adminCreateCombo)
	router.Put("/combos/{id}", s.adminUpdateCombo)
	router.Delete("/combos/{id}", s.adminDeleteCombo)
	router.Get("/combos/{id}/statistics", s.adminComboStatistics)
	router.Get("/squad-products", s.adminSquadProducts)
	router.Post("/squad-products", s.adminCreateSquadProduct)
	router.Put("/squad-products/{id}", s.adminUpdateSquadProduct)
	router.Get("/squad-products/{id}/nodes", s.adminSquadNodes)
	router.Put("/squad-products/{id}/nodes", s.adminUpdateSquadNodes)
	router.Get("/squad-products/{id}/statistics", s.adminSquadStatistics)
	router.Post("/squad-products/import", s.adminImportSquads)
	router.Get("/users", s.adminUsers)
	router.Get("/users/{id}", s.adminUser)
	router.Post("/users/{id}/balance-adjustments", s.adminBalanceAdjustment)
	router.Get("/entitlements", s.adminEntitlements)
	router.Post("/entitlements/{id}/cancel", s.adminCancelEntitlement)
	router.Get("/payments", s.adminPayments)
	router.Post("/payments/{id}/refund", s.adminRefundPayment)
	router.Post("/payments/{id}/courtesy-credit", s.adminCourtesyCreditPayment)
	router.Get("/refunds", s.adminRefunds)
	router.Get("/backups", s.adminBackups)
	router.Post("/backups", s.adminCreateBackup)
	router.Delete("/backups/{id}", s.adminDeleteBackup)
	router.Get("/jobs", s.adminJobs)
	router.Post("/jobs/{id}/retry", s.adminRetryJob)
	router.Delete("/jobs/{id}", s.adminDeleteJob)
	router.Get("/audit-events", s.adminAuditEvents)
	router.Get("/onboarding/content/{kind}", s.adminOnboardingBundle)
	router.Put("/onboarding/content/{kind}/draft", s.adminSaveOnboardingDraft)
	router.Post("/onboarding/content/{kind}/publish", s.adminPublishOnboarding)
}
