package httpapi

import (
	"github.com/go-chi/chi/v5"
)

func (s *Server) mountAdmin(router chi.Router) {
	s.mountCommunityAdmin(router)
	router.Get("/emby-accounts", s.adminEmbyAccounts)
	router.Post("/emby-accounts/{id}/retry", s.retryAdminEmbyAccount)
	router.Get("/settings", s.adminSettings)
	router.Post("/settings", s.adminCreateSetting)
	router.Put("/settings/{key}", s.adminUpdateSetting)
	router.Put("/billing/amount-limits", s.adminUpdateBillingAmountLimits)
	router.Get("/payment-profiles", s.adminPaymentProfiles)
	router.Post("/payment-profiles", s.adminCreatePaymentProfile)
	router.Put("/payment-profiles/{id}", s.adminSavePaymentProfile)
	router.Get("/combos", s.adminCombos)
	router.Post("/combos", s.adminCreateCombo)
	router.Put("/combos/{id}", s.adminUpdateCombo)
	router.Delete("/combos/{id}", s.adminDeleteCombo)
	router.Get("/combos/{id}/statistics", s.adminComboStatistics)
	router.Get("/squad-products", s.adminSquadProducts)
	router.Post("/squad-products", s.adminCreateSquadProduct)
	router.Put("/squad-products/{id}", s.adminUpdateSquadProduct)
	router.Get("/squad-products/{id}/statistics", s.adminSquadStatistics)
	router.Post("/squad-products/import", s.adminImportSquads)
	router.Get("/users", s.adminUsers)
	router.Get("/users/{id}", s.adminUser)
	router.Post("/users/{id}/balance-adjustments", s.adminBalanceAdjustment)
	router.Put("/users/{userId}/entitlements/{entitlementId}", s.adminEditEntitlement)
	router.Post("/users/{userId}/entitlements/{entitlementId}/refund", s.adminRefundEntitlement)
	router.Post("/users/{userId}/combo-replacement", s.adminReplaceCombo)
	router.Post("/operations/{operationId}/resolve", s.adminResolveOperation)
	router.Post("/bulk-extensions/preview", s.adminPreviewBulkExtension)
	router.Post("/bulk-extensions", s.adminCreateBulkExtension)
	router.Get("/entitlements", s.adminEntitlements)
	router.Post("/entitlements/{id}/cancel", s.adminCancelEntitlement)
	router.Get("/payments", s.adminPayments)
	router.Post("/payments/{id}/refund", s.adminRefundPayment)
	router.Post("/payments/{id}/courtesy-credit", s.adminCourtesyCreditPayment)
	router.Get("/refunds", s.adminRefunds)
	router.Get("/backups", s.adminBackups)
	router.Post("/backups", s.adminCreateBackup)
	router.Delete("/backups/{id}", s.adminDeleteBackup)
	router.Get("/jobs", s.adminJobs)
	router.Post("/jobs/{id}/retry", s.adminRetryJob)
	router.Delete("/jobs/{id}", s.adminDeleteJob)
	router.Get("/audit-events", s.adminAuditEvents)
	router.Get("/onboarding/content/{kind}", s.adminOnboardingBundle)
	router.Put("/onboarding/content/{kind}/draft", s.adminSaveOnboardingDraft)
	router.Post("/onboarding/content/{kind}/publish", s.adminPublishOnboarding)
}
