// Package notifications formats and delivers durable private Telegram events.
package notifications

const (
	FactCombo              = "combo"
	FactExpires            = "expires"
	FactExpired            = "expired"
	FactAutoRenewal        = "autoRenewal"
	FactQueuedCombo        = "queuedCombo"
	FactTrafficLimit       = "trafficLimitBytes"
	FactReset              = "reset"
	FactAddOns             = "addOns"
	FactValidUntil         = "validUntil"
	FactRenewalDebit       = "renewalDebitMinor"
	FactUsed               = "usedBytes"
	FactAllocated          = "allocatedBytes"
	FactEligible           = "eligibleBytes"
	FactRollover           = "rolloverMinor"
	FactRolloverStatus     = "rolloverStatus"
	FactBalance            = "balanceMinor"
	FactRemaining          = "remainingBytes"
	FactMessages           = "messages"
	FactReward             = "rewardMinor"
	FactTime               = "time"
	FactChange             = "change"
	FactAmount             = "amountMinor"
	FactCredited           = "creditedMinor"
	FactCancelledCombos    = "cancelledCombos"
	FactAddedSeconds       = "addedSeconds"
	FactPreviousExpiry     = "previousExpiry"
	FactNewExpiry          = "newExpiry"
	FactPreviousCombo      = "previousCombo"
	FactNewCombo           = "newCombo"
	FactPreviousValidFrom  = "previousValidFrom"
	FactNewValidFrom       = "newValidFrom"
	FactPreviousStatus     = "previousStatus"
	FactNewStatus          = "newStatus"
	FactPreviousTraffic    = "previousTrafficBytes"
	FactNewTraffic         = "newTrafficBytes"
	FactPreviousReset      = "previousReset"
	FactNewReset           = "newReset"
	FactPreviousSquads     = "previousSquads"
	FactNewSquads          = "newSquads"
	FactReason             = "reason"
	FactCharge             = "chargeMinor"
	FactAutomationState    = "automationState"
	FactNode               = "node"
	FactAffectedSquads     = "affectedSquads"
	FactOutageStarted      = "outageStarted"
	FactRecovered          = "recovered"
	FactDowntimeSeconds    = "downtimeSeconds"
	FactCompensationCapped = "compensationCapped"
)
